name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  license:
    name: Check license header
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: apache/skywalking-eyes/header@v0.4.0
        with:
          config: tools/ci/licenserc.yml

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - run: cargo build --workspace --all-features
    - run: cargo clippy --workspace --tests --all-features -- -D warnings
    - run: cargo fmt --all -- --check
    - run: cargo test --workspace --all-features
