name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  license:
    name: Check license header
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: apache/skywalking-eyes/header@v0.4.0
        with:
          config: tools/ci/licenserc.yml

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - uses: Swatinem/rust-cache@v1

    - name: Cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Check clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace --tests --all-features -- -D warnings

    - name: Check format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --workspace
